In [1]:
from __init__ import *
import itertools

In [2]:
def get_frontal_faces_2(A):
    return(set(itertools.product(*[list(range(dim)) for dim in A.shape[2:]])))

In [3]:
A = np.ones((3000,1000,300,3))

In [4]:
one = get_frontal_faces(A)

In [5]:
two = get_frontal_faces_2(A)

In [3]:
from trpca import *

In [13]:
import time

start = time.time()
b = get_frontal_faces_2(A)
end = time.time()
print(end - start)

0.0


In [14]:
import time

start = time.time()
b = get_frontal_faces(A)
end = time.time()
print(end - start)

0.0


In [7]:
A = np.random.normal(0,1,(2,2,2))


In [9]:
u,s,v=t_SVD(A)

In [16]:
t_prod(t_prod(u,s),v) - A

array([[[ 0.00000000e+00+0.j, -1.11022302e-16+0.j],
        [ 2.22044605e-16+0.j, -5.55111512e-16+0.j]],

       [[ 0.00000000e+00+0.j,  0.00000000e+00+0.j],
        [ 2.22044605e-16+0.j,  2.77555756e-17+0.j]]])

In [14]:
t_prod(v,t_transpose(v))

array([[[ 1.00000000e+00+0.j, -3.33066907e-16+0.j],
        [ 0.00000000e+00+0.j,  0.00000000e+00+0.j]],

       [[ 0.00000000e+00+0.j,  0.00000000e+00+0.j],
        [ 1.00000000e+00+0.j, -3.33066907e-16+0.j]]])

In [13]:
s

array([[[1.76573762+0.j, 0.13608793+0.j],
        [0.        +0.j, 0.        +0.j]],

       [[0.        +0.j, 0.        +0.j],
        [0.58423831+0.j, 0.53978539+0.j]]])